# Generated by Django 4.2.5 on 2023-09-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_professor_department_professor_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_group',
            new_name='group',
        ),
    ]
