# Generated by Django 4.2.5 on 2023-09-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_groupmarks_groupmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'verbose_name': 'Курс-группа', 'verbose_name_plural': 'Курсы-группы'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='groupmark',
            options={'verbose_name': 'Группа оценок', 'verbose_name_plural': 'Группы оценок'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentmark',
            options={'verbose_name': 'Оценкки студента', 'verbose_name_plural': 'Оценки студентов'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='patronymic',
            new_name='last_name',
        ),
    ]
