# Generated by Django 4.2.5 on 2023-09-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_second_name_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='additional',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дополнительные баллы'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='att1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка за аттестацию 1'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='att2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка за аттестацию 2'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='att3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка за аттестацию 3'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='exam',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка за экзамен'),
        ),
    ]
